server:
  port: 8002
  servlet:
    context-path: /content-service
spring:
  datasource:
    url: jdbc:mysql://muteki.top:3306/user_center?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: xzx233
    driver-class-name: com.mysql.cj.jdbc.Driver