GET http://localhost:8001/user-service/hello
Accept: application/json
###
GET http://localhost:8000/user-service/hello
Accept: application/json
###
GET http://localhost:8000/user-service/user/count
Accept: application/json
token: {{token}}
###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json


{
  "phone": "13951905171",
  "password": "123123"
}
> {%
   client.global.set("token",response.body.data.token);


 %}
###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json


{
  "phone": "13951905172",
  "password": "123123"
}
> {%
    client.global.set("token",response.body.data.token);


%}
###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json


{
  "password": "1231233"
}

###
POST http://localhost:8000/user-service/user/register
Content-Type: application/json


{
  "phone": "13951905781",
  "password": "88888"
}

###
GET http://localhost:8000/content-service/share/notice
Accept: application/json
###
GET http://localhost:8000/content-service/share/list
Accept: application/json
###
GET http://localhost:8000/content-service/share/list?title=并发编程
Accept: application/json
###
GET http://localhost:8000/content-service/share/list
Accept: application/json
token: {{token}}
###
GET http://localhost:8000/content-service/share/list?pageNo=3&pageSize=2
Accept: application/json
token: {{token}}
###
GET http://localhost:8000/content-service/share/1
Accept: application/json
token: {{token}}
###
PUT http://localhost:8000/user-service/user/update-bonus
content-type: application/json
token: {{token}}

{
  "userId": 1,
  "bonus": -11
}
###
GET http://localhost:8000/user-service/user/1
Accept: application/json
token: {{token}}
###
POST http://localhost:8000/content-service/share/exchange
content-type: application/json
Accept: application/json
token: {{token}}

{
  "userId": 2,
  "shareId": 22
}
###
POST http://localhost:8000/content-service/share/contribute
content-type: application/json
Accept: application/json
token: {{token}}

{
  "userId": 2,
  "author": "峰哥",
  "title": "详解 Vue.js",
  "isOriginal": 1,
  "price": 500,
  "downloadUrl": "https://www.bilibili.com",
  "cover": "https://tse1-mm.cn.bing.net/th/id/OIP-C.GtURKnUv3GgvsXNh8o8UqAHaHa?pid=ImgDet&rs=1",
  "summary": "资本峰勇闯天涯，揭秘印度手抓饭"
}
###
GET http://localhost:8000/content-service/share/my-contribute?pageNo=2&pageSize=2
Accept: application/json
token: {{token}}
###
GET http://localhost:8000/content-service/share/admin/list
Accept: application/json
token: {{token}}