GET http://localhost:8001/user-service/hello
Accept: application/json
###
GET http://localhost:8000/user-service/hello
Accept: application/json
###
GET http://localhost:8000/user-service/user/count
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2OTY2Njc5NjYsInBob25lIjoiMTM5NTE5MDUxNzEiLCJpZCI6MSwiZXhwIjoxNjk2NjY4OTY2LCJpYXQiOjE2OTY2Njc5NjZ9.12VimtsYvp-tHnVhiTr-kKI2ucpyVitpBjtiI1EK81I
###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json


{
  "phone": "13951905171",
  "password": "123123"
}
###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json


{
  "password": "1231233"
}

###
POST http://localhost:8000/user-service/user/register
Content-Type: application/json


{
  "phone": "13951905781",
  "password": "88888"
}